// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lpixrvtsmplgicqaqrxx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxwaXhydnRzbXBsZ2ljcWFxcnh4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ1OTk0ODYsImV4cCI6MjA2MDE3NTQ4Nn0.Zth41Ciz6QmmuaG67m8t2L86wRBR0vdsWFNLQagsnS4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);